<?php
/**
 * @category   Installment
 * @package    Installment_Installment
 * @author     eng.noooor.307@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Installment\Installment\Block;

use Magento\Framework\View\Element\Template\Context;
use Installment\Installment\Model\InstallmentFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Installment View block
 */
class InstallmentView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Installment
     */
    protected $_installment;
    public function __construct(
        Context $context,
        InstallmentFactory $installment,
        FilterProvider $filterProvider
    ) {
        $this->_installment = $installment;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Installment Installment Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $installment = $this->_installment->create();
        $singleData = $installment->load($id);
        if($singleData->getInstallmentId() || $singleData['installment_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}