<?php
/**
 * @category   Installment
 * @package    Installment_Installment
 * @author     eng.noooor.307@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Installment\Installment\Block;

use Magento\Framework\View\Element\Template\Context;
use Installment\Installment\Model\InstallmentFactory;
/**
 * Installment List block
 */
class InstallmentListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Installment
     */
    protected $_installment;

    protected $_storeManager;

    public function __construct(
        Context $context,
        \Magento\Store\Model\StoreManagerInterface $storeManager, 
        InstallmentFactory $installment
    ) {
        $this->_storeManager = $storeManager;
        $this->_installment = $installment;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
//        $this->pageConfig->getTitle()->set(__('Installment Installment Module List Page'));
        
        if ($this->getInstallmentCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'installment.installment.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getInstallmentCollection()
            );
            $this->setChild('pager', $pager);
            $this->getInstallmentCollection()->load();
        }
        return parent::_prepareLayout();
    }


    /**
     * Get store identifier
     *
     * @return  int
     */
    public function getStoreId()
    {
        return $this->_storeManager->getStore()->getId();
    }

    /**
     * Get Store code
     *
     * @return string
     */
    public function getStoreCode()
    {
        return $this->_storeManager->getStore()->getCode();
    }

    public function getInstallmentCollection()
    {
//         $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
//         $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $installmentvalu = $this->_installment->create();
        $collectionvalu = $installmentvalu->getCollection();
        $collectionvalu->addFieldToFilter('status','1');
//        $collectionvalu->addFieldToFilter('payment_method','1'); // valu
//        $collectionvalu->setOrder('plans','ASC');
        // $collection->setPageSize($pageSize);
        // $collection->setCurPage($page);

        return $collectionvalu;
    }

    public function getInstallmentCollectionValu()
    {
        // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $installmentvalu = $this->_installment->create();
        $collectionvalu = $installmentvalu->getCollection();
        $collectionvalu->addFieldToFilter('status','1');
        $collectionvalu->addFieldToFilter('payment_method','1'); // valu
        $collectionvalu->setOrder('plans','ASC');
        // $collection->setPageSize($pageSize);
        // $collection->setCurPage($page);

        return $collectionvalu;
    }

    public function getInstallmentCollectionSohola()
    {
        // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $installmentsohla = $this->_installment->create();
        $collectionsohola = $installmentsohla->getCollection();
        
        $collectionsohola->addFieldToFilter('status','1'); //shola
        $collectionsohola->addFieldToFilter('payment_method','2');
       // $collection->addFieldToFilter('payment_method', array('eq'=>1))
        $collectionsohola->setOrder('plans','ASC');
        // $collection1->setPageSize($pageSize);
        // $collection1->setCurPage($page);

       // print_r($collection->getData());

      

        return $collectionsohola;
    }
 

  public function getInstallmentCollectionForsa()
  {
      // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
      // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

      $installmentforsa = $this->_installment->create();
      $collectionforsa = $installmentforsa->getCollection();
      
      $collectionforsa->addFieldToFilter('status','1'); 
      $collectionforsa->addFieldToFilter('payment_method','3');
     // $collection->addFieldToFilter('payment_method', array('eq'=>1))
      $collectionforsa->setOrder('plans','ASC');
      // $collection1->setPageSize($pageSize);
      // $collection1->setCurPage($page);

     // print_r($collection->getData());

    

      return $collectionforsa;
  }


  public function getInstallmentCollectionCib()
  {
      // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
      // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

      $installmentcib = $this->_installment->create();
      $collectioncib = $installmentcib->getCollection();
      
      $collectioncib->addFieldToFilter('status','1'); 
      $collectioncib->addFieldToFilter('payment_method','4');
     // $collection->addFieldToFilter('payment_method', array('eq'=>1))
      $collectioncib->setOrder('plans','ASC');
      // $collection1->setPageSize($pageSize);
      // $collection1->setCurPage($page);

     // print_r($collection->getData());

    

      return $collectioncib;
  }


  public function getInstallmentCollectionMisr()
  {
      // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
      // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

      $installmentmisr = $this->_installment->create();
      $collectionmisr = $installmentmisr->getCollection();
      
      $collectionmisr->addFieldToFilter('status','1'); 
      $collectionmisr->addFieldToFilter('payment_method','5');
     // $collection->addFieldToFilter('payment_method', array('eq'=>1))
      $collectionmisr->setOrder('plans','ASC');
      // $collection1->setPageSize($pageSize);
      // $collection1->setCurPage($page);

     // print_r($collection->getData());

    

      return $collectionmisr;
  }


  public function getInstallmentCollectionMashreq()
  {
      // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
      // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

      $installmentmashreq = $this->_installment->create();
      $collectionmashreq = $installmentmashreq->getCollection();
      
      $collectionmashreq->addFieldToFilter('status','1'); 
      $collectionmashreq->addFieldToFilter('payment_method','6');
     // $collection->addFieldToFilter('payment_method', array('eq'=>1))
      $collectionmashreq->setOrder('plans','ASC');
      // $collection1->setPageSize($pageSize);
      // $collection1->setCurPage($page);

     // print_r($collection->getData());

    

      return $collectionmashreq;
  }


  public function getInstallmentCollectionBdc()
  {
      // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
      // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

      $installmentbdc = $this->_installment->create();
      $collectionbdc = $installmentbdc->getCollection();
      
      $collectionbdc->addFieldToFilter('status','1'); 
      $collectionbdc->addFieldToFilter('payment_method','7');
     // $collection->addFieldToFilter('payment_method', array('eq'=>1))
      $collectionbdc->setOrder('plans','ASC');
      // $collection1->setPageSize($pageSize);
      // $collection1->setCurPage($page);

     // print_r($collection->getData());

    

      return $collectionbdc;
  }



  public function getInstallmentCollectionNbe()
  {
      // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
      // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

      $installmentnbe = $this->_installment->create();
      $collectionnbe = $installmentnbe->getCollection();
      
      $collectionnbe->addFieldToFilter('status','1'); 
      $collectionnbe->addFieldToFilter('payment_method','8');
     // $collection->addFieldToFilter('payment_method', array('eq'=>1))
      $collectionnbe->setOrder('plans','ASC');
      // $collection1->setPageSize($pageSize);
      // $collection1->setCurPage($page);

     // print_r($collection->getData());

    

      return $collectionnbe;
  }


  public function getInstallmentCollectionFab()
  {
      // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
      // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

      $installmentfab = $this->_installment->create();
      $collectionfab = $installmentfab->getCollection();
      
      $collectionfab->addFieldToFilter('status','1'); 
      $collectionfab->addFieldToFilter('payment_method','9');
     // $collection->addFieldToFilter('payment_method', array('eq'=>1))
      $collectionfab->setOrder('plans','ASC');
      // $collection1->setPageSize($pageSize);
      // $collection1->setCurPage($page);

     // print_r($collection->getData());

    

      return $collectionfab;
  }
 

  public function getInstallmentCollectionNbd()
  {
      // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
      // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

      $installmentnbd = $this->_installment->create();
      $collectionnbd = $installmentnbd->getCollection();
      
      $collectionnbd->addFieldToFilter('status','1'); 
      $collectionnbd->addFieldToFilter('payment_method','10');
     // $collection->addFieldToFilter('payment_method', array('eq'=>1))
      $collectionnbd->setOrder('plans','ASC');
      // $collection1->setPageSize($pageSize);
      // $collection1->setCurPage($page);

     // print_r($collection->getData());

    

      return $collectionnbd;
  }


  public function getInstallmentCollectionNbk()
  {
      // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
      // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

      $installmentnbk = $this->_installment->create();
      $collectionnbk = $installmentnbk->getCollection();
      
      $collectionnbk->addFieldToFilter('status','1'); 
      $collectionnbk->addFieldToFilter('payment_method','11');
     // $collection->addFieldToFilter('payment_method', array('eq'=>1))
      $collectionnbk->setOrder('plans','ASC');
      // $collection1->setPageSize($pageSize);
      // $collection1->setCurPage($page);

     // print_r($collection->getData());

    

      return $collectionnbk;
  }


  public function getInstallmentCollectionAman()
  {
      // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
      // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

      $installmentaman = $this->_installment->create();
      $collectionaman = $installmentaman->getCollection();
      
      $collectionaman->addFieldToFilter('status','1'); 
      $collectionaman->addFieldToFilter('payment_method','12');
     // $collection->addFieldToFilter('payment_method', array('eq'=>1))
      $collectionaman->setOrder('plans','ASC');
      // $collection1->setPageSize($pageSize);
      // $collection1->setCurPage($page);

     // print_r($collection->getData());

    

      return $collectionaman;
  }


  public function getInstallmentCollectionkhazna()
  {
      // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
      // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

      $installmentkhazna = $this->_installment->create();
      $collectionkhazna = $installmentkhazna->getCollection();
      
      $collectionkhazna->addFieldToFilter('status','1'); 
      $collectionkhazna->addFieldToFilter('payment_method','13');
     // $collection->addFieldToFilter('payment_method', array('eq'=>1))
      $collectionkhazna->setOrder('plans','ASC');
      // $collection1->setPageSize($pageSize);
      // $collection1->setCurPage($page);

     // print_r($collection->getData());

    

      return $collectionkhazna;
  }


  public function getInstallmentCollectionBlnk()
  {
      // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
      // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

      $installmentblnk = $this->_installment->create();
      $collectionblnk = $installmentblnk->getCollection();
      
      $collectionblnk->addFieldToFilter('status','1'); 
      $collectionblnk->addFieldToFilter('payment_method','14');
     // $collection->addFieldToFilter('payment_method', array('eq'=>1))
      $collectionblnk->setOrder('plans','ASC');
      // $collection1->setPageSize($pageSize);
      // $collection1->setCurPage($page);

     // print_r($collection->getData());

    

      return $collectionblnk;
  }

    public function getInstallmentCollectionContact()
    {
        // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $installmentcontact = $this->_installment->create();
        $collectioncontact = $installmentcontact->getCollection();

        $collectioncontact->addFieldToFilter('status','1');
        $collectioncontact->addFieldToFilter('payment_method','15');
        // $collection->addFieldToFilter('payment_method', array('eq'=>1))
        $collectioncontact->setOrder('plans','ASC');
        // $collection1->setPageSize($pageSize);
        // $collection1->setCurPage($page);

        // print_r($collection->getData());



        return $collectioncontact;
    }



    public function getInstallmentCollectionAdib()
    {
        // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $installmentadib = $this->_installment->create();
        $collectionadib = $installmentadib->getCollection();

        $collectionadib->addFieldToFilter('status','1');
        $collectionadib->addFieldToFilter('payment_method','16');
        // $collection->addFieldToFilter('payment_method', array('eq'=>1))
        $collectionadib->setOrder('plans','ASC');
        // $collection1->setPageSize($pageSize);
        // $collection1->setCurPage($page);

        // print_r($collection->getData());



        return $collectionadib;
    }

    public function getInstallmentCollectionAub()
    {
        // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $installmentaub = $this->_installment->create();
        $collectionaub = $installmentaub->getCollection();

        $collectionaub->addFieldToFilter('status','1');
        $collectionaub->addFieldToFilter('payment_method','17');
        // $collection->addFieldToFilter('payment_method', array('eq'=>1))
        $collectionaub->setOrder('plans','ASC');
        // $collection1->setPageSize($pageSize);
        // $collection1->setCurPage($page);

        // print_r($collection->getData());



        return $collectionaub;
    }
    public function getInstallmentCollectionAi()
    {
        // $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        // $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $installmentai = $this->_installment->create();
        $collectionai = $installmentai->getCollection();

        $collectionai->addFieldToFilter('status','1');
        $collectionai->addFieldToFilter('payment_method','18');
        // $collection->addFieldToFilter('payment_method', array('eq'=>1))
        $collectionai->setOrder('plans','ASC');
        // $collection1->setPageSize($pageSize);
        // $collection1->setCurPage($page);

        // print_r($collection->getData());



        return $collectionai;
    }
    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}