<?php
/**
 * @category   Installment
 * @package    Installment_Installment
 * @author     eng.noooor.307@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Installment\Installment\Model\ResourceModel;

class Installment extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('installment_installment', 'installment_id');   //here "installment_installment" is table name and "installment_id" is the primary key of custom table
    }
}