<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Quick Order for Magento 2
 */
?>

<aside class="amqorder-popup-block"
       data-amqorder-js="popup"
       data-bind="
            scope:'popup',
            mageInit: {
             'Magento_Ui/js/core/app': <?= $block->escapeHtml($block->getJsLayout()) ?>
         }"
       aria-hidden="true">
    <!-- ko template: getTemplate() --><!-- /ko -->
</aside>
