<?php
/**
 * @category   Installment
 * @package    Installment_Installment
 * @author     eng.noooor.307@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Installment\Installment\Model\Source;

use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;
use Magento\Eav\Model\Entity\Attribute\Source\SourceInterface;
use Magento\Framework\Data\OptionSourceInterface;

/**
 * Item Paymentmethod functionality model
 */
class Paymentmethod extends AbstractSource implements SourceInterface, OptionSourceInterface
{
    /**#@+
     * Item Status values
     */
    const PAY_VALU = 1;
    const PAY_SOHOLA = 2;
    const PAY_FORSA = 3;
    const PAY_CIB = 4;
    const PAY_MISR = 5;
    const PAY_MASHREQ = 6;
    const PAY_BDC = 7;
    const PAY_NBE = 8;
    const PAY_HSBC = 9;
    const PAY_NBD = 10;
    const PAY_NBK = 11;
    const PAY_AMAN = 12;
    const PAY_KHAZNA = 13;
    const PAY_BLNK = 14;
    const PAY_CONTACT = 15;

    const PAY_ADIB = 16;
    const PAY_AUB = 17;
    const PAY_AI = 18;


    /**#@-*/

    /**
     * Retrieve option array
     *
     * @return string[]
     */
    public static function getOptionArrayPayment()
    {
        return [self::PAY_VALU => __('valu'), self::PAY_SOHOLA => __('Sohola'), self::PAY_FORSA => __('Forsa'), self::PAY_CIB => __('CIB'), self::PAY_MISR => __('Misr'), self::PAY_MASHREQ => __('Mashreq'), self::PAY_BDC => __('Bdc'), self::PAY_NBE => __('Nbe'), self::PAY_HSBC => __('HSBC'), self::PAY_NBD => __('Nbd'), self::PAY_NBK => __('Nbk'), self::PAY_AMAN => __('Aman'), self::PAY_CONTACT => __('Contact'), self::PAY_KHAZNA => __('Khazna'), self::PAY_BLNK => __('Blnk'), self::PAY_ADIB => __('Adib'), self::PAY_AUB => __('Aub'), self::PAY_ADIB => __('Ai')];
    }

    /**
     * Retrieve option array with empty value
     *
     * @return string[]
     */
    public function getAllOptions()
    {
        $result = [];

        foreach (self::getOptionArrayPayment() as $index => $value) {
            $result[] = ['value' => $index, 'label' => $value];
        }

        return $result;
    }
}