<?php
/**
 * @category   Installment
 * @package    Installment_Installment
 * @author     eng.noooor.307@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Installment\Installment\Model\Source;

use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;
use Magento\Eav\Model\Entity\Attribute\Source\SourceInterface;
use Magento\Framework\Data\OptionSourceInterface;

/**
 * Item Plans functionality model
 */
class Plans extends AbstractSource implements SourceInterface, OptionSourceInterface
{
    /**#@+
     * Item Status values
     */
    const PLAN_1MONTH = 1;
    const PLAN_2MONTH = 2;
    const PLAN_3MONTH = 3;
    const PLAN_6MONTH = 6;
    const PLAN_9MONTH = 9;
    const PLAN_12MONTH = 12;
    const PLAN_15MONTH = 15;
    const PLAN_18MONTH = 18;
    const PLAN_21MONTH = 21;
    const PLAN_24MONTH = 24;
    const PLAN_27MONTH = 27;
    const PLAN_30MONTH = 30;
    const PLAN_33MONTH = 33;
    const PLAN_36MONTH = 36;
    const PLAN_39MONTH = 39;
    const PLAN_42MONTH = 42;
    const PLAN_45MONTH = 45;
    const PLAN_48MONTH = 48;
    const PLAN_51MONTH = 51;
    const PLAN_54MONTH = 54;
    const PLAN_57MONTH = 57;
    const PLAN_60MONTH = 60;
    const PLAN_61MONTH = 61;



    /**#@-*/

    /**
     * Retrieve option array
     *
     * @return string[]
     */
    public static function getOptionArrayPlan()
    {
        return [self::PLAN_1MONTH => __('1 Month'),self::PLAN_2MONTH => __('2 Month'),self::PLAN_3MONTH => __('3 Month'), self::PLAN_6MONTH => __('6 Month'), self::PLAN_9MONTH => __('9 Month'), self::PLAN_12MONTH => __('12 Month'), self::PLAN_15MONTH => __('15 Month'), self::PLAN_18MONTH => __('18 Month'), self::PLAN_21MONTH => __('21 Month'), self::PLAN_24MONTH => __('24 Month'), self::PLAN_27MONTH => __('27 Month'), self::PLAN_30MONTH => __('30 Month'), self::PLAN_33MONTH => __('33 Month'), self::PLAN_36MONTH => __('36 Month'), self::PLAN_39MONTH => __('39 Month'), self::PLAN_42MONTH => __('42 Month'), self::PLAN_45MONTH => __('45 Month'), self::PLAN_48MONTH => __('48 Month'), self::PLAN_51MONTH => __('51 Month'), self::PLAN_54MONTH => __('54 Month'), self::PLAN_57MONTH => __('57 Month'), self::PLAN_60MONTH => __('60 Month'), self::PLAN_61MONTH => __('61 Month')];
    }

    /**
     * Retrieve option array with empty value
     *
     * @return string[]
     */
    public function getAllOptions()
    {
        $result = [];

        foreach (self::getOptionArrayPlan() as $index => $value) {
            $result[] = ['value' => $index, 'label' => $value];
        }

        return $result;
    }
}