<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Quick Order for Magento 2
 */
/** @var \Amasty\QuickOrder\Block\Category\ProductList $block */
?>

<?php if (!$block->getProductCollection()->count()):?>
        <div class="message info empty">
            <div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
        </div>
<?php else:?>
    <?= /* @noEscape */ $block->getToolbarHtml() ?>

    <div class="amqorder-products-wrapper products wrapper">
        <?= /* @noEscape */ $block->getGridHtml() ?>
    </div>

    <?= /* @noEscape */ $block->getToolbarHtml(true) ?>
<?php endif; ?>
