<?php
/**
 * @category   Installment
 * @package    Installment_Installment
 * @author     eng.noooor.307@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Installment\Installment\Block\Adminhtml\Items\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;

//use Installment\PaymentInstallment\Model\PaymentInstallmentFactory;



class Main extends Generic implements TabInterface
{
    protected $_wysiwygConfig;

//       /**
//     * @var PaymentInstallment
//     */
//    protected $_paymentinstallment;
 
    public function __construct(
        \Magento\Backend\Block\Template\Context $context, 
        \Magento\Framework\Registry $registry, 
        \Magento\Framework\Data\FormFactory $formFactory,  
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig, 
//        PaymentInstallmentFactory $paymentinstallment,
        array $data = []
    ) 
    {
        $this->_wysiwygConfig = $wysiwygConfig;
        parent::__construct($context, $registry, $formFactory, $data);
//        $this->_paymentinstallment = $paymentinstallment;
    }

    /**
     * {@inheritdoc}
     */
    public function getTabLabel()
    {
        return __('Item Information');
    }

    /**
     * {@inheritdoc}
     */
    public function getTabTitle()
    {
        return __('Item Information');
    }

    /**
     * {@inheritdoc}
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function isHidden()
    {
        return false;
    }


    // public function getPaymentInstallmentCollection()
    // {
    //   //   $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
    //   //   $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;
  
    //     $paymentinstallment = $this->_paymentinstallment->create();
    //     $collectionalll = $paymentinstallment->getCollection();
    //     $collectionalll->addFieldToFilter('status','1');
    //     //$paymentinstallment->setOrder('paymentinstallment_id','ASC');
    //     //$collection->setPageSize($pageSize);
    //     //$collection->setCurPage($page);

        
  
    //     return $collectionalll;
    // }



    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    protected function _prepareForm()
    {

//        $paymentinstallment = $this->_paymentinstallment->create();
//        $collectionalll = $paymentinstallment->getCollection();
//        $collectionalll->addFieldToFilter('status','1');
        //$paymentinstallment->setOrder('paymentinstallment_id','ASC');
        //$collection->setPageSize($pageSize);
        //$collection->setCurPage($page);

        
        // foreach($collectionalll as $valu)
        // {

        //     $valu->getpaymentinstallment_id();
        //     $valu->gettitle();

        // }
        
        
    
        

        $model = $this->_coreRegistry->registry('current_installment_installment_items');
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('item_');
        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('Item Information')]);
        if ($model->getId()) {
            $fieldset->addField('installment_id', 'hidden', ['name' => 'installment_id']);
        }
        $fieldset->addField(
            'status',
            'select',
            ['name' => 'status', 'label' => __('Status'), 'title' => __('Status'),  'options'   => [0 => 'Disable', 1 => 'Enable'], 'required' => true]
        );
   
     
        $fieldset->addField(
            'payment_method',
            'select',
            ['name' => 'payment_method', 'label' => __('payment_method'), 'title' => __('payment_method'),'options'   => [1 => 'valu', 2 => 'Souhoola',3 => 'Forsa',4 => 'CIB',5 => 'MISR',6 => 'Mashreq',7 => 'Banque du Caire',8 => 'NBE',9 => 'HSBC',10 => 'NBD',11 => 'NBK',12 => 'aman',13 => 'khazna',14 => 'blnk',15 => 'Contact',16 => 'Adib Bank',17 => 'Aub Bank',18 => 'Ai Bank'], 'required' => true]
        
            );


      
  
        $fieldset->addField(
            'plans',
            'select',
            ['name' => 'plans', 'label' => __('plans'), 'title' => __('plans'),  'options'   => [1 => '1 Month',2 => '2 Month',3 => '3 Month',4 => '4 Month',5 => '5 Month', 6 => '6 Month',9 => '9 Month',12 => '12 Month',15 => '15 Month',18 => '18 Month',21 => '21 Month',24 => '24 Month',27 => '27 Month',30 => '30 Month',33 => '33 Month',36 => '36 Month',39 => '39 Month',42 => '42 Month',45 => '45 Month',48 => '48 Month',51 => '51 Month',54 => '54 Month',57 => '57 Month',60 => '60 Month',61 => '61 Month'], 'required' => true]
        );

        $fieldset->addField(
            'interestfees',
            'text',
            ['name' => 'interestfees', 'label' => __('Interset Fees'), 'title' => __('Interset Fees'), 'required' => true]
        );



        $fieldset->addField(
            'status_interestfees',
            'select',
            ['name' => 'status_interestfees', 'label' => __('Using Spicial Price '), 'title' => __('Using Spicial Price'),  'options'   => [0 => 'Disable', 1 => 'Enable'], 'required' => true]
        );


        $fieldset->addField(
            'discount_installment',
            'select',
            ['name' => 'discount_installment', 'label' => __('Using Discount '), 'title' => __('Using Discount'),  'options'   => [0 => 'Disable', 1 => 'Enable'], 'required' => true]
        );

        $fieldset->addField(
            'discount_fees',
            'text',
            ['name' => 'discount_fees', 'label' => __('Discount Fees'), 'title' => __('Discount Fees')]
        );

        // $fieldset->addField(
        //     'discount_en_title',
        //     'text',
        //     ['name' => 'discount_en_title', 'label' => __('Title Discount English'), 'title' => __('Title Discount English')]
        // );

        // $fieldset->addField(
        //     'discount_ar_title',
        //     'text',
        //     ['name' => 'discount_ar_title', 'label' => __('Title Discount Arabic'), 'title' => __('Title Discount Arabic')]
        // );




          //  $fieldset->addField(
        //     'status_different',
        //     'text',
        //     ['name' => 'status_different', 'label' => __('Title Purshaed Fees Arabic'), 'title' => __('Title Purshaed Fees Arabic')]
        // );

         //  $fieldset->addField(
        //     'status_adding',
        //     'text',
        //     ['name' => 'status_adding', 'label' => __('Title CashBack Fees Arabic'), 'title' => __('Title CashBack Fees Arabic')]
        // );

      



        $fieldset->addField(
            'status_purshedfees',
            'select',
            ['name' => 'status_purshedfees', 'label' => __('status purshedfees'), 'title' => __('status purshedfees'),  'options'   => [0 => 'Disable', 1 => 'Enable'], 'required' => true]
        );

        $fieldset->addField(
            'title',
            'text',
            ['name' => 'title', 'label' => __('Title Purshaed Fees English'), 'title' => __('Title Purshaed Fees English'), 'required' => true]
        );

      

        $fieldset->addField(
            'add',
            'text',
            ['name' => 'add', 'label' => __('Title Purshaed Fees Arabic'), 'title' => __('Title Purshaed Fees Arabic'), 'required' => true]
        );

        $fieldset->addField(
            'purshedfees',
            'text',
            ['name' => 'purshedfees', 'label' => __('purashed Fees'), 'title' => __('purashed Fees')]
        );


        $fieldset->addField(
            'status_cashbackfees',
            'select',
            ['name' => 'status_cashbackfees', 'label' => __('status cashbackfees'), 'title' => __('status cashbackfees'),  'options'   => [0 => 'Disable', 1 => 'Enable'], 'required' => true]
        );

       

        $fieldset->addField(
            'different',
            'text',
            ['name' => 'different', 'label' => __('Title CashBack Fees English'), 'title' => __('Title CashBack Fees English')]
        );

       

            $fieldset->addField(
            'content',
            'text',
            [
                'name' => 'content',
                'label' => __('Title CashBack Fees Arabic'),
                'title' => __('Title CashBack Fees Arabic'),
                'config'    => $this->_wysiwygConfig->getConfig(),
                'wysiwyg' => true
            ]
        );


        $fieldset->addField(
            'cashbackfees',
            'text',
            ['name' => 'cashbackfees', 'label' => __('Cashback Fees'), 'title' => __('Cashback Fees')]
        );
        



       

        



        // $fieldset->addField(
        //     'image',
        //     'image',
        //     [
        //         'name' => 'image',
        //         'label' => __('Image'),
        //         'title' => __('Image'),
        //         'required'  => false
        //     ]
        // );
       
        // $fieldset->addField(
        //     'content',
        //     'editor',
        //     [
        //         'name' => 'content',
        //         'label' => __('Content'),
        //         'title' => __('Content'),
        //         'style' => 'height:26em;',
        //         'required' => true,
        //         'config'    => $this->_wysiwygConfig->getConfig(),
        //         'wysiwyg' => true
        //     ]
        // );
        
        $form->setValues($model->getData());
        $this->setForm($form);
        return parent::_prepareForm();
    }
}
