<?php
/**
* Copyright © 2017 Codazon, Inc. All rights reserved.
* See COPYING.txt for license details.
*/

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$helper = $this->helper('Codazon\ThemeLayoutPro\Helper\Data');
?>
<?php if ($helper->getConfig('pages/product_view/display_social_links')) : ?>
<?php
$productHelper = $this->helper('Magento\Catalog\Helper\Output');
$imageHelper = $this->helper('Magento\Catalog\Helper\Image');
$_product = $this->getProduct();
$url = urlencode($this->stripTags($block->getProductUrl($_product)));
$desc = urlencode($this->stripTags($_product->getShortDescription()));
$image = urlencode($imageHelper->init($_product, 'image')->setImageFile($_product->getImage())->resize(1000)->getUrl());
$name = urlencode($this->stripTags($productHelper->productAttribute($_product, $_product->getName(), 'name')));
//    $image = urldecode($image);
    $totalurl = urlencode($url . '?img=' . $image);
//    &picture=<?= $image; ?>

<ul class="cdz-social-listing">
    <li class="cdz-facebook">
        <a onclick='window.open("https://www.facebook.com/sharer/sharer.php?u=<?= $url; ?>","","menubar=1,resizable=1,width=700,height=600")'  target="_blank" href="javascript:void(0)" title="<?= __('Share on Facebook') ?>"><svg xmlns="http://www.w3.org/2000/svg" height="16" width="16" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2023 Fonticons, Inc.--><path d="M512 256C512 114.6 397.4 0 256 0S0 114.6 0 256C0 376 82.7 476.8 194.2 504.5V334.2H141.4V256h52.8V222.3c0-87.1 39.4-127.5 125-127.5c16.2 0 44.2 3.2 55.7 6.4V172c-6-.6-16.5-1-29.6-1c-42 0-58.2 15.9-58.2 57.2V256h83.6l-14.4 78.2H287V510.1C413.8 494.8 512 386.9 512 256h0z"/></svg></a>
    </li>
    <li class="cdz-twitter">
        <a onclick='window.open("https://twitter.com/intent/tweet?url=<?= $url; ?>&text=<?= $desc ?>","","menubar=1,resizable=1,width=700,height=600")' rel="nofollow" target="_blank" href="javascript:void(0)" title="<?= __('Share on Twitter') ?>"><svg xmlns="http://www.w3.org/2000/svg" height="16" width="14" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2023 Fonticons, Inc.--><path d="M64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H384c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64zm297.1 84L257.3 234.6 379.4 396H283.8L209 298.1 123.3 396H75.8l111-126.9L69.7 116h98l67.7 89.5L313.6 116h47.5zM323.3 367.6L153.4 142.9H125.1L296.9 367.6h26.3z"/></svg></a>
    </li>
    <li class="cdz-linkedin">
        <a onclick='window.open("https://www.linkedin.com/shareArticle?mini=true&url=<?= $url; ?>&title=<?= $name ?>&ro=false&summary=<?= $desc ?>&source=","","menubar=1,resizable=1,width=700,height=600")' rel="nofollow" title="<?= __('Share on LinkedIn') ?>"  target="_blank" href="javascript:void(0)"><svg xmlns="http://www.w3.org/2000/svg" height="16" width="14" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2023 Fonticons, Inc.--><path d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z"/></svg></a>
    </li>


    
    <?php /* <li class="cdz-twitter">
        <a onclick='window.open("https://twitter.com/intent/tweet?url=<?= $url; ?>&text=<?= $desc ?>","","menubar=1,resizable=1,width=700,height=600")' rel="nofollow" target="_blank" href="javascript:void(0)" title="<?= __('Share on Twitter') ?>"><i class="fa-brands fa-square-x-twitter"></i></a>
    </li> */ ?>  
    <?php /* <li class="cdz-google-plus">
        <a onclick='window.open("https://plus.google.com/share?url=<?= $url; ?>","","menubar=1,resizable=1,width=700,height=600")' rel="nofollow" title="<?= __('Share on Google+') ?>"
        class="js-cdz-tooltip" target="_blank" href="javascript:void(0)"><i class="fa fa-google-plus"></i></a>
    </li> */ ?>
    <?php /* <li class="cdz-instagram">
        <a onclick='window.open("https://instagram.com/send?url=<?= $url; ?>&media=<?= $image ?>&description=<?= $desc ?>","","menubar=1,resizable=1,width=700,height=600")' rel="nofollow" title="<?= __('Insagram This') ?>" target="_blank" href="javascript:void(0)"><i class="fa fa-insagram"></i></a>
    </li>  */ ?>
    <?php /* <li class="cdz-whatsapp">
        <a onclick='window.open("https://api.whatsapp.com/send?url=<?= $url; ?>&media=<?= $image ?>&description=<?= $desc ?>","","menubar=1,resizable=1,width=700,height=600")' rel="nofollow" title="<?= __('Whatsapp This') ?>" target="_blank" href="javascript:void(0)"><i class="fa fa-whatsapp"></i></a>
    </li> */ ?>
    <?php /* <li class="cdz-pinterest">
        <a onclick='window.open("https://www.pinterest.com/pin/create/a/?url=<?= $url; ?>&media=<?= $image ?>&description=<?= $desc ?>","","menubar=1,resizable=1,width=700,height=600")' rel="nofollow" title="<?= __('Pin this') ?>" target="_blank" href="javascript:void(0)"><i class="fa fa-pinterest"></i></a>
    </li> */ ?>
    <?php if ($this->canEmailToFriend()): ?>
    <li class="cdz-email">
        <a href="<?= $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>" title="<?= __('Email') ?>"
       class="mailto friend" target="_blank"><i class="fa fa-envelope"></i></a>
    </li>
    <?php endif ?>
</ul>
<?php endif ?>