<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Quick Order for Magento 2
 */

/**
 * @var $block \Magento\Bundle\Block\Adminhtml\Catalog\Product\Composite\Fieldset\Options\Type\Select
 * @var \Magento\Framework\Escaper $escaper
 */

$_option      = $block->getOption();
$_selections  = $_option->getSelections();
$_default     = $_option->getDefaultSelection();
//phpcs:disable
//@phpstan-ignore-next-line
$_skipSaleableCheck = $this->helper(Magento\Catalog\Helper\Product::class)->getSkipSaleableCheck();
//phpcs:enable
list($_defaultQty, $_canChangeQty) = $block->getDefaultValues();
?>

<div class="amqorder-option-wrapper">
    <label class="amqorder-label <?= /* @noEscape */ $_option->getRequired() ? '-required' : '' ?>">
        <span><?= $escaper->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="amqorder-option -select">
        <?php if ($block->showSingle()): ?>
            <?= /* @noEscape */ $block->getSelectionTitlePrice($_selections[0]) ?>
            <input type="hidden"
                   class="bundle-option-<?= (int)$_option->getId() ?> product bundle option"
                   name="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                   price="<?= $escaper->escapeHtmlAttr($block->getSelectionPrice($_selections[0])) ?>"
                   value="<?= $escaper->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"/>
        <?php else: ?>
            <div class="amqorder-options-list">
                <select id="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>"
                                    name="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                                    class="amqorder-select bundle option <?= /* @noEscape */ $_option->getRequired() ? 'required-entry' : '' ?>">
                    <option value=""><?= $escaper->escapeHtml(__('Choose a selection...')) ?></option>
                                <?php foreach ($_selections as $_selection): ?>
                                    <option
                                        value="<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                                        <?= /* @noEscape */ $block->isSelected($_selection) ? 'selected="selected"' : '' ?>
                                        <?= (!$_selection->isSaleable() && !$_skipSaleableCheck) ? ' disabled="disabled"' : '' ?>
                                        price="<?= $escaper->escapeHtmlAttr($block->getSelectionPrice($_selection)) ?>"
                                        qtyId="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>-qty-input">
                            <?= /* @noEscape */ $block->getSelectionTitlePrice($_selection, false) ?>
                        </option>
                                <?php endforeach; ?>
                </select>
            </div>
        <?php endif; ?>
        <div class="amqorder-qty-block <?= /* @noEscape */ !$_canChangeQty ? '-disabled' : '' ?>"
             data-mage-init='{"amqorderQty": {}}'>
            <div class="amqorder-qty-wrapper" data-amqorder-js="qty-wrapper">
                <input id="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>-qty-input"
                       class="amqorder-input qty <?= /* @noEscape */ !$_canChangeQty ? 'qty-disabled' : '' ?>"
                       type="number"
                       min="0"
                       name="bundle_option_qty[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                       data-amqorder-js="input"
                       data-selector="bundle_option_qty[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                       value="<?= $escaper->escapeHtmlAttr($_defaultQty) ?>"
                    <?= $_canChangeQty ? '' : ' disabled="disabled"' ?>/>
            </div>
        </div>
    </div>
</div>
