<?php
/**
 * @category   Installment
 * @package    Installment_Installment
 * @author     eng.noooor.307@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Installment\Installment\Controller\Index;

use Magento\Framework\App\Action\Context;
use Magento\Framework\Exception\NotFoundException;
use Installment\Installment\Block\InstallmentView;

class View extends \Magento\Framework\App\Action\Action
{
	protected $_installmentview;

	public function __construct(
        Context $context,
        InstallmentView $installmentview
    ) {
        $this->_installmentview = $installmentview;
        parent::__construct($context);
    }

	public function execute()
    {
    	if(!$this->_installmentview->getSingleData()){
    		throw new NotFoundException(__('Parameter is incorrect.'));
    	}
    	
        $this->_view->loadLayout();
        $this->_view->getLayout()->initMessages();
        $this->_view->renderLayout();
    }
}
