<?php
/**
 * Webkul DailyDeals Product Edit
 *
 * @category  Webkul
 * @package   Webkul_DailyDeals
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$dealsDateTime = $block->getDealsDateTime();
?>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        $('body').trigger('contentUpdated');
    });
</script>
<?php
if ($dealsDateTime) { ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "setattribute": {
                    "dealFrom": "<?= /* @noEscape */ $dealsDateTime['deal_from_date'] ?>",
                    "dealTo": "<?= /* @noEscape */ $dealsDateTime['deal_to_date'] ?>",
                    "dateFormat" : "<?= /* @noEscape */ $dealsDateTime['date_format'] ?>",
                    "moduleEnable" : "<?= /* @noEscape */ $dealsDateTime['module_enable'] ?>",
                    "productType" : "<?= /* @noEscape */ $dealsDateTime['product_type'] ?>"
                }
            }
        }
    </script>
<?php } ?>
